### ISSUE TITLE
cannot import name 'base' from partially initialized module

### ISSUE THREAD

**Issue by Queenslandes** [jmoortgat/DeepRiverFCN#2]
运行inference_fcnn.py进行验证时出现以下错误
Traceback (most recent call last):
  File "/content/DeepRiverFCN/inference_fcnn.py", line 9, in <module>
    import segmentation_models as sm
  File "/content/DeepRiverFCN/segmentation_models/__init__.py", line 1, in <module>
    from .segmentation_models import *
  File "/content/DeepRiverFCN/segmentation_models/segmentation_models/__init__.py", line 4, in <module>
    from . import base
ImportError: cannot import name 'base' from partially initialized module 'segmentation_models.segmentation_models' (most likely due to a circular import) (/content/DeepRiverFCN/segmentation_models/segmentation_models/__init__.py)
没有在项目中找到相对应的base模块，我是菜鸟，请求解答，感谢！！

**Comment by jmoortgat** [comment]
Apologies for the very late reply — I wasn't monitoring this repository's issues.

You found a real bug, and it's now fixed on `main` (commit a656015). The root cause: the copy of `segmentation_models` committed to this repository was incomplete — its `__init__.py` imports `base`, `losses`, and `utils` submodules that were never committed, so `import segmentation_models` failed on any fresh clone (our local working copies had the complete package, which is why we never hit it).

The vendored copy has been removed entirely; the code now uses the upstream pip package. To run the current version:

```bash
git pull
pip install -r requirements.txt
```

This also works on modern TensorFlow (≥ 2.16): the scripts now set `TF_USE_LEGACY_KERAS=1` (using the `tf_keras` shim) and `SM_FRAMEWORK=tf.keras` automatically. Thanks for the report.

**Comment by jmoortgat** [comment]
Fixed in a656015 — closing. Feel free to reopen if you still hit problems with the current main.
